shipuznik/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("shipuznik2.urls")),
]

shipuznik2/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('', views.registration, name = 'home'),
    path('show', views.show, name = 'show'),
    path('login', views.login, name = 'login'),
    path('add_project', views.add_project, name = 'add_project'),
    path('search',views.search, name = 'search'),
    path('registration',views.registration, name = 'registration'),
    path('browse',views.browse, name = 'browse'),
    path('my_profile', views.my_profile, name = 'my_profile'),
    path('my_projects', views.my_projects, name = 'my_projects'),
    path('my_profile_worker', views.my_profile_worker, name = 'my_profile_worker'),
    path('user', views.user, name = 'user'),
    path('worker', views.worker, name = 'worker'),
    path('test', views.test, name = 'test'),
    path('projects/<int:project_id>/', views.restapi_projects, name='restapi_projects'),
    path('my_quotas', views.my_quotas, name = 'my_qoutas'),
    path('readme', views.readme, name = 'readme'),
    

]
# name is the redirect

shipuznik2/models.py
from django.db import models

# Create your models here.


class Worker(models.Model):
    name = models.CharField(max_length=256)
    phone = models.CharField(max_length=256)
    email = models.CharField(max_length=256)
    city = models.CharField(max_length=256)
    password =  models.CharField( max_length=256, default="")

    def __str__(self) -> str:
        return super().__str__()
    
class User(models.Model):
    name = models.CharField(max_length=256)
    phone = models.CharField(max_length=256)
    city = models.CharField(max_length=256)
    password =  models.CharField( max_length=256, default="")

    def __str__(self) -> str:
        return super().__str__()
    

    
    
class Skills(models.Model):
    skill_name = models.CharField(max_length=256)
    skill_description = models.TextField(default="")
    workers = models.ManyToManyField(Worker)
    

    def __str__(self) -> str:
        return super().__str__()
    
class Project(models.Model):
    name = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    skill_id = models.ForeignKey(Skills,on_delete=models.CASCADE)
    worker_id =  models.ForeignKey(Worker,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return super().__str__()
    
class Price(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    amount = models.IntegerField()
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE, null=True, blank=True, default=None)

shipuznik2/views.py
from django.shortcuts import render
from .models import Worker,Skills,User,Project,Price
from django.http import HttpResponse
from django.db.models import Q

# Create your views here.

def registration(request):
    if request.method == "GET":
        skills = Skills.objects.all() 
        return render(request, "registration.html", {"skills": skills})

    if request.method == "POST":
        name = request.POST["name"]
        phone = request.POST["phone"]
        email = request.POST["email"]
        city = request.POST["city"]
        type =request.POST["type"]
        password = request.POST["password"]
        skills = Skills.objects.all()
        if type == "worker":
            worker = Worker(name = name, phone = phone, email = email, city = city, password = password)
            worker.save()
            #Skills.objects.get(skill_name=skill).workers.add(worker) adding a skill while registrating
            return render(request, "registration.html",{"skills": skills})
        if type == "user":
            user = User(name = name, phone = phone, city = city, password = password)
            user.save()
            return render(request, "registration.html",{"skills": skills})

def show(request):
    if request.method == "GET":
        worker = Worker.objects.all()
    return render(request, "show.html", {"worker":  worker})

def login(request):
    if request.method == "GET":
        return render(request, "login.html")
    if request.method == "POST":
        name = request.POST["name"]
        password = request.POST["password"]
        type = request.POST["type"]
        if type == "worker":   
            input_name = Worker.objects.filter(name = name ).values_list('password', flat = True)
            print("hey")
            print(name)
            print(input_name[0])
            print(password)
            print("check check")
            print(type)
            if password == input_name[0]:
                request.session['username'] = request.POST["name"]
                request.session['type'] = request.POST["type"]
                print("check check2222")
                print(request.session['type'])
                return HttpResponse("session created a worker is logged in")
            else:
                return HttpResponse("a worker is not authorized")
        elif type == "user" :
            input_name = User.objects.filter(name = name ).values_list('password', flat = True)
            print(input_name[0])
            print(password)
            print("check check")
            if password == input_name[0]:
                request.session['username'] = request.POST["name"]
                request.session['type'] = request.POST["type"]
                return HttpResponse("session created an user is logged in")
            else:
                return HttpResponse(" an user is not authorized")


def add_project(request):
    if request.method == "GET":
        print("fckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkc")
        skills = Skills.objects.all()
        workers = Worker.objects.all()
        return render(request, "add_project.html",{"skills": skills, "workers":workers})
    if request.method == "POST":
        print("sdlfjdslfsjflajs;dfjasdfkjaslfkjadslfkasdjflkasdjfalskfnalsdkfsadl")
        name = request.POST["name"]
        description = request.POST["description"]
        skill = request.POST["skill_id"]
        worker = request.POST["worker_id"]
        print(skill)
        user  = User.objects.filter(name=request.session['username']).values_list("id", flat=True).first()
        skills = Skills.objects.all()
        workers = Worker.objects.all()
        Project.objects.create(name = name, description = description,
        skill_id_id = skill, user_id_id = user, worker_id_id = worker)
        return render(request, "add_project.html",{"skills": skills, "workers":workers})
    

def search(request):
    if request.method == "GET":
        return render(request, "search.html")
    if request.method == "POST":
        query = request.POST["q"]
        results = Worker.objects.filter(
        Q(name__icontains=query) | 
        Q(email__icontains=query) | 
        Q(city__icontains=query)
    )
    return render(request, "search.html", {"results": results})

def browse(request):
    if request.method == "GET":
        worker = Worker.objects.all()
        skills = Skills.objects.all()
        return render(request, "browse.html",{"worker" : worker,"skills": skills})
    if request.method == "POST":
        city = request.POST["city"]
        skills = request.POST["skill"]
        workers2 = Worker.objects.filter(city = city, skills = skills)
        print(workers2)
        worker = Worker.objects.all()
        skills = Skills.objects.all()
        return render(request, "browse.html", {"workers2":  workers2, "worker" : worker,"skills": skills })
    
def my_profile(request):
    if request.method == "GET":
        if request.session['type'] == "user":
            print(request.session['type'])
            name = request.session['username']
            return render(request, "user.html",{"name": name})
        elif request.session['type'] == "worker":
            print("welcome checkk")
            print(request.session['type'])
            name = request.session['username']
            return render(request, "worker.html",{"name": name})
        else:
            print("Unknown session type:", request.session['type'])

def user(request):
    if request.method == "GET":
        return render(request, "user.html")
    

def worker(request):
    if request.method == "GET":
        return render(request, "worker.html")
        
def my_profile_worker(request):
     if request.method == "GET":
        projects =  Project.objects.all()
        return render(request, "my_profile_worker.html",{"projects": projects})
     if request.method == "POST":
        projects =  Project.objects.all()
        prices = Price.objects.all
        price = request.POST["price"]
        worker_id = Worker.objects.filter(name = request.session['username']).values_list("id", flat= True).first()
        print(request.session['username'])
        id = request.POST["id"]
        print("checkcheck 33333")
        print(id)
        print(price)
        print(request.session['username'])
        print("wrong")
        Price.objects.create(amount = price, project_id = id, worker_id = worker_id)
        return render(request, "my_profile_worker.html",{"projects": projects, "prices": prices})


def my_projects(request):
    if request.method == "GET":
        if request.session['type'] == "user":
            print(request.session['type'])
            name = request.session['username']
            user_id = User.objects.filter(name = name).values_list("id", flat= True).first()
            print("check check")
            print(user_id)
            project = Project.objects.all().filter(user_id_id = user_id)
            return render(request, "my_projects.html",{"name": name, "projects": project})
        if request.session['type'] == "worker":
            print(request.session['type'])
            return render(request, "my_projects.html")
        


    
def restapi_projects(request, project_id):
     if request.method == "GET":
        project = Project.objects.get(pk=project_id)
        return render(request, "restapi_project.html", {"project": project})
     if request.method == "POST":
        project = Project.objects.get(pk=project_id)
        price = request.POST["price"]
        project_id = project_id
        worker_id = Worker.objects.filter(name = request.session['username']).values_list("id", flat= True).first()
        Price.objects.create(amount = price, project_id = project_id, worker_id = worker_id)
        return render(request, "restapi_project.html", {"project": project})
     

    
def my_quotas(request,):
     if request.method == "GET":
        name = request.session['username']
        worker_id = Worker.objects.filter(name = name).values_list("id", flat= True).first()
        prices = Price.objects.all().filter(worker_id = worker_id)
        print(prices)
        return render(request, "my_quotas.html", {"prices": prices})
     
def readme(request,):
     if request.method == "GET":
        return render( request,  "readme.html")


def test(request):
     if request.method == "GET":
        projects =  Project.objects.all()
        return render(request, "test.html",{"projects": projects})
     if request.method == "POST":
        projects =  Project.objects.all()
        prices = Price.objects.all
        price = request.POST["price"]
        worker_id = Worker.objects.filter(name = request.session['username']).values_list("id",flat  =True).first()
        print(request.session['username'])
        id = request.POST["id"]
        print("checkcheck 33333")
        print(id)
        print(price)
        print(request.session['username'])
        print("wrong")
        Price.objects.create(amount = price, project_id = id, worker_id = worker_id)
        return render(request, "test.html",{"projects": projects})
         

shipuznik2/templates/add_project.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <div class="wrapper">
        <div class="nav">
            <div class="nav-item"><a href="/registration" class="am">REGISTRATION</a></div>
            <div class="nav-item"><a href="/login" class="am">LOGIN</a></div>
            <div class="nav-item"><a href="/my_profile" class="am">PROFILE</a></div>
            <div class="nav-item"><a href="/browse" class="am">BROWSE</a></div>
            <div class="nav-item"><a href="/my_profile_worker" class="am">worker</a></div>
            <div class="nav-item"><a href="/">admin restapi</a></div>
            
        </div>
        <div class="mom">
            <div class="mininav">
                <div class="nav-item2"><a href="/my_profile" class="am1">MY PROFILE</a></div>
                <div class="nav-item2"><a href="/my_projects" class="am1">PROJECTS</a></div>
                <div class="nav-item2"><a href="/add_project" class="am1" >ADD/EDIT NEW PROJECT</a></div>
            </div>
            <div class="form">
                <form action="" method="POST"> 
                    <h3>ADD PROJECT</h3>
                    <input type="text" name="name" placeholder="name">
                    <input type="text" name="description" placeholder="description">
                    <select name="skill_id">
                        {% for skill in skills %}
                        <option value={{skill.id}}>{{skill.skill_name}}</option>
                        {% endfor %}
                    </select>

                    <select name="worker_id">
                        {% for worker in workers %}
                        <option value={{worker.id}}>{{worker.name}}</option>
                        {% endfor %}
                    </select>
                <input type="submit">
                </form>
            </div>
         </div>
        </div>
    </div>
{% endblock content %}

shipuznik2/templates/browse.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <div class="wrapper">
        <div class="nav">
            <div class="nav-item"><a href="/registration" class="am">REGISTRATION</a></div>
            <div class="nav-item"><a href="/login" class="am">LOGIN</a></div>
            <div class="nav-item"><a href="/my_profile" class="am">PROFILE</a></div>
            <div class="nav-item"><a href="/browse" class="am">BROWSE</a></div>
            <div class="nav-item"><a href="/my_profile_worker" class="am">WORKER</a></div>
            <div class="nav-item"><a href="/readme " class="am">README</a></div>
            
        </div>
        <div class="mom">
            <div class="form">
                <div class="headline"> Look for Workers
                </div> <br>
                <form action="" method="POST"> 
                    <select name="skill">
                        {% for skill in skills %}
                        <option value={{skill.id}}>{{skill.skill_name}}</option>
                        {% endfor %}
                    </select>
                    <select name="city">
                        {% for worker in worker %}
                        <option value={{worker.city}}>{{worker.city}}</option>
                        {% endfor %}
                    </select>
                <input type="submit">
                </form>
                    <div class="grid-container">
                        <div class="headline">Worker Name</div>
                        <div class="headline"> Phone  </div>
                        <div class="headline"> Skill</div>
                        <div class="headline"> id</div>
                        {% for worker in workers2 %}
                        <div>{{worker.name}}</div>
                        <div>{{worker.phone}}</div>
                        <div></div>
                        <div></div>
                        {% endfor %}
                      </div>
            </div>
         </div>
        </div>
    </div>
{% endblock content %}

shipuznik2/templates/footer.html
</body>
</html>

shipuznik2/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

</head>
<body>

shipuznik2/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <div class="wrapper">
        <div class="nav">
            <div class="nav-item"><a href="/profile">Profile</a></div>
            <div class="nav-item"><a href="/">registration</a></div>
            <div class="nav-item"><a href="/">projects</a></div>
            <div class="nav-item"><a href="/login">login</a></div>
            <div class="nav-item"><a href="/">admin restapi</a></div>
            
        </div>
        <div class="mom">
            <div class="form">
                <form action="" method="post">
                <input type="text" name="name" placeholder="name"> <br>
                <input type="text" name="email" placeholder="email"> <br>
                <input type="text" name="phone" placeholder="phone"> <br>
                <input type="text" name="city" placeholder="city"> <br>
                <select name="type">
                    {% for skill in skills %}
                    <option value={{skill.skill_name}}>{{skill.skill_name}}</option>
                    {% endfor %}
                <input type="submit">
                </select>
                </form>
            </div>
         </div>
        </div>
    </div>

{% endblock content %}

shipuznik2/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <div class="wrapper">
        <div class="nav">
            <div class="nav-item"><a href="/registration" class="am">REGISTRATION</a></div>
            <div class="nav-item"><a href="/login" class="am">LOGIN</a></div>
            <div class="nav-item"><a href="/my_profile" class="am">PROFILE</a></div>
            <div class="nav-item"><a href="/browse" class="am">BROWSE</a></div>
            <div class="nav-item"><a href="/my_profile_worker" class="am">WORKER</a></div>
            <div class="nav-item"><a href="/readme " class="am">README</a></div>
            
        </div>
        <div class="mom">
            <div class="form">
                <form action="" method="POST"> 
                    <div class="headline"> LOGIN
                         </div> <br>
                    <input type="text" name="name" placeholder="name">
                    <input type="text" name="password" placeholder="password">
                    <select name="type">
                    <option value="user">User</option>
                    <option value="worker">Worker</option>    
                    
                <input type="submit">
                </select>
                </form>
            </div>
         </div>
        </div>
    </div>

{% endblock content %}

shipuznik2/templates/my_profile.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="wrapper">
        <div class="nav">
            <div class="nav-item"><a href="/registration" class="am">REGISTRATION</a></div>
            <div class="nav-item"><a href="/login" class="am">LOGIN</a></div>
            <div class="nav-item"><a href="/my_profile" class="am">PROFILE</a></div>
            <div class="nav-item"><a href="/browse" class="am">BROWSE</a></div>
            <div class="nav-item"><a href="/my_profile_worker" class="am">WORKER</a></div>
            <div class="nav-item"><a href="/readme " class="am">README</a></div>
            
        </div>
        <div class="mom">
            <div class="mininav">
                <div class="nav-item2"><a href="/my_profile" class="am1">MY PROFILE</a></div>
                <div class="nav-item2"><a href="/my_projects" class="am1">PROJECTS</a></div>
                <div class="nav-item2"><a href="/add_project" class="am1" >ADD/EDIT NEW PROJECT</a></div>
                <div class="nav-item2"><a href="/add_project" class="am1" >WORKER</a></div>
            </div>
            <div class="form">
                <div class="headline"> welcome back, {{ name }}
                </div> <br>
                <input type="submit">
                </form>
            </div>
         </div>
        </div>
    </div>
{% endblock content %}

shipuznik2/templates/my_profile_worker.html
{% extends "base.html" %}
{% block content %}

<style>
  .tableshmock {
      font-size: 11px;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      border-collapse: collapse;
      width: 80%;
      border-radius: 10px;
      overflow: hidden;   
      background-color: rgba(48, 126, 164, 0.3);
  }

  .tableshmock th, .tableshmock td {
      padding: 12px 15px;
      text-align: left;
      border-bottom: 1px solid #ddd;
  }

  .tableshmock tr:nth-child(even) {
      background-color: #f2f2f2;
  }

  .tableshmock tr:hover {
      background-color: rgb(245, 169, 178);
  }

  
input {
  width: 50px;
}
input[type="text"] {
    font-size: 11px;
}
input[type="submit"] {
    font-size: 11px;
}

a.open:visited {
  color: brown;
  
}

a.open:hover {
  color: cornflowerblue;
}



</style>
    <div class="container">
    <div class="wrapper">
      <div class="nav">
        <div class="nav-item"><a href="/registration" class="am">REGISTRATION</a></div>
            <div class="nav-item"><a href="/login" class="am">LOGIN</a></div>
            <div class="nav-item"><a href="/my_profile" class="am">PROFILE</a></div>
            <div class="nav-item"><a href="/browse" class="am">BROWSE</a></div>
            <div class="nav-item"><a href="/my_profile_worker" class="am">WORKER</a></div>
            <div class="nav-item"><a href="/readme " class="am">README</a></div>
    </div>

        <div class="mom">
            <div class="mininav">
                <div class="nav-item2"><a href="/my_profile" class="am1">MY PROFILE</a></div>
                <div class="nav-item2"><a href="/my_quotas" class="am1">MY QUOTAS</a></div>
                <div class="nav-item2"><a href="/my_profile_worker" class="am1">BROWSE PROJECTS</a></div>
            </div>
            <div class="form">
            
                <div class="headline"> Here you can Check all of the Projects
                </div> <br>
                <table class="tableshmock">
                    <tr>
                        <th>Name Of The Project</th>
                        <th>Skill Required</th>
                        <th>Submitted Prices So Far</th>
                        <th>Available Actions</th>
                      </tr>
                
                      {% for project in projects %}
                      <tr>
                      <form action="" method="POST">
                          <th>{{ project.name }}</th>
                          <th>{{ project.skill_id.skill_name }}</th>
                          <th>
                            <select name="" id="price">
                              {% for price in project.price_set.all %}
                                <option value="{{ price.amount }}">{{ price.amount }}</option>
                              {% endfor %}
                            </select>
                            <input type="hidden" value="{{ project.id }}" name="id">
                          </th>
                          <th>
                            {{ project.price }}
                            <input type="text" name="price" placeholder="price">
                            <input type="submit">
                            <a class="open" href="/projects/{{ project.id }}" target="_blank">OPEN PROJECT</a>
                          </th>
                        
                      </form>
                      </tr>
                    {% endfor %}
            </div>
         </div>
        </div>
    </div>
{% endblock content %}

shipuznik2/templates/my_projects.html
{% extends "base.html" %}
{% block content %}
<style>
  .grid-container {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-gap: 10px;
    align-items: center;
  }

  .headline {
    font-weight: bold;
    font-size: 16px;
  }

  .item {
    padding: 10px;
    background-color: rgba(48, 126, 164, 0.3);
    border-radius: 10px;
    overflow: hidden;
  }
</style>
<div class="container">
  <div class="wrapper">
    <div class="nav">
      <div class="nav-item"><a href="/registration" class="am">REGISTRATION</a></div>
      <div class="nav-item"><a href="/login" class="am">LOGIN</a></div>
      <div class="nav-item"><a href="/my_profile" class="am">PROFILE</a></div>
      <div class="nav-item"><a href="/browse" class="am">BROWSE</a></div>
      <div class="nav-item"><a href="/my_profile_worker" class="am">WORKER</a></div>
      <div class="nav-item"><a href="/readme" class="am">README</a></div>
    </div>
    <div class="mom">
      <div class="mininav">
        <div class="nav-item2"><a href="/my_profile" class="am1">MY PROFILE</a></div>
        <div class="nav-item2"><a href="/my_projects" class="am1">PROJECTS</a></div>
        <div class="nav-item2"><a href="/add_project" class="am1">ADD/EDIT NEW PROJECT</a></div>
      </div>
      <div class="form">
        <div class="headline"> welcome back, {{ name }}, here are the upcoming projects
        </div> <br>
        <div class="grid-container">
          <div class="headline item">Project Name</div>
          <div class="headline item">Date</div>
          <div class="headline item">Skill Required</div>
          <div class="headline item">Chosen Worker</div>
          {% for project in projects %}
          <div class="item">{{project.name}}</div>
          <div class="item">{{project.date}}</div>
          <div class="item">{{ project.skill_id.skill_name }}</div>
          <div class="item">{{project.worker_id.name}}</div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

shipuznik2/templates/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <div class="wrapper">
        <div class="nav">
            <div class="nav-item"><a href="/">login 2 users</a></div>
            <div class="nav-item"><a href="/">registration</a></div>
            <div class="nav-item"><a href="/">projects</a></div>
            <div class="nav-item"><a href="/login">login</a></div>
            <div class="nav-item"><a href="/">admin restapi</a></div>
            
        </div>
        <div class="mom">
            <div class="form">
                <form action="" method="POST"> 
                    <h3>this is profile, create new project</h3>
                    <input type="text" name="name" placeholder="name">
                    <input type="text" name="description" placeholder="description">
                    <select name="skill_id">
                        {% for skill in skills %}
                        <option value={{skill.id}}>{{skill.id}}</option>
                        {% endfor %}
                    </select>
                <input type="submit">
                </form>
            </div>
         </div>
        </div>
    </div>
{% endblock content %}

shipuznik2/templates/readme.html
{% extends "base.html" %}
{% block content %}

<style>
    .texterino{
        width: 100%;
        padding: 10px;
    }
</style>
    <div class="container">
    <div class="wrapper">
        <div class="nav">
            <div class="nav-item"><a href="/registration" class="am">REGISTRATION</a></div>
            <div class="nav-item"><a href="/login" class="am">LOGIN</a></div>
            <div class="nav-item"><a href="/my_profile" class="am">PROFILE</a></div>
            <div class="nav-item"><a href="/browse" class="am">BROWSE</a></div>
            <div class="nav-item"><a href="/my_profile_worker" class="am">WORKER</a></div>
            <div class="nav-item"><a href="/readme " class="am">README</a></div>
            
        </div>
        <div class="mom">
            <div class="form">
                <textarea name="" id="" cols="30" rows="20" class="texterino">
                    

Functionality, Features, and How to Start:

Important note: This platform does not support anonymous browsing. You must register and log in to use the platform.

To use the platform, you can register as a user or worker. Currently, most features are available for the worker category. Once you log in, you can go to your profile and browse all existing projects. You can submit the price either in a separate window or in the browsing window. You can also see the quotas you have submitted.

As a user, the features are currently limited. You can create a project and attach a worker to it. Alternatively, in the navigation bar, you can browse workers according to their skills and city. Please note that only Israeli cities are available in the platform. To select an Israeli city, scroll down and choose a city, such as "painting".

For testing purposes, you can use the following credentials: as a user, name: "user", password: "user"; as a worker, name: "worker", password: "worker".



                </textarea>
            </div>
         </div>
        </div>
    </div>

{% endblock content %}

shipuznik2/templates/search.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <div class="wrapper">
        <div class="nav">
            <div class="nav-item"><a href="/registration">REGISTRATION</a></div>
            <div class="nav-item"><a href="/login">LOGIN</a></div>
            <div class="nav-item"><a href="/profile">PROFILE</a></div>
            <div class="nav-item"><a href="/">login</a></div>
            <div class="nav-item"><a href="/">admin restapi</a></div>
            
        </div>
        <div class="mom">
            <div class="form">
                <form action="" method="post">
                <input type="text" name="q" placeholder="search"> <br>
                <input type="submit">
                </select>
                </form>
                <table>
                    <thead>
                        <tr>
                            <th>name</th>
                            <th>email</th>
                            <th>city</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for r in results %}
                        <tr>
                            <td>{{ r.name }}</td>
                            <td>{{ r.email }}</td>
                            <td>{{ r.city }}</td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
         </div>
        </div>
    </div>

{% endblock content %}